### ISSUE TITLE
Convert all references to SimpleSAML_* to namespaces

### ISSUE THREAD

**Issue by BAGELreflex** [cirrusidentity/simplesamlphp-module-authoauth2#13]
I am running the latest version of SimpleSAMLphp (1.17.2). Using **NOTICE** logging, I am receiving the following in my **simplesamlphp.log**:

> Apr 08 11:09:36 simplesamlphp WARNING [477adde4a0] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
> Apr 08 11:09:46 simplesamlphp WARNING [477adde4a0] The class or interface 'SimpleSAML_Configuration' is now using namespaces, please use 'SimpleSAML\Configuration'.

The following files have references to a class using the old `\SimpleSAML_Foo_Bar`. These need to be updated to use namespaces, such as `\SimpleSAML\Foo\Bar`.

- lib/Auth/Source/OAuth2.php
- lib/OAuth2ResponseHandler.php
- tests/config/config.php
- tests/lib/Auth/Source/MicrosoftHybridAuthTest.php
- tests/lib/Auth/Source/OAuth2Test.php
- tests/lib/OAuth2ResponseHandlerTest.php
- www/errors/consent.php

**Comment by pradtke** [comment]
Thanks @BAGELreflex 
We'll address this soon.

**Comment by djdevin** [comment]
Hastily updated all the calls to use namespaces.'

Bumped composer.json so it requires SSP 1.17.
