### ISSUE TITLE
Missing Class error

### ISSUE THREAD

**Issue by umardraz** [cirrusidentity/simplesamlphp-module-authoauth2#28]
Hello I am getting the following error

`[Fri Nov 01 13:13:09.487429 2019] [php7:error] [pid 13035:tid 140422881249024] [client 119.158.1.160:60840] PHP Fatal error:  Class 'League\\OAuth2\\Client\\Provider\\GenericProvider' not found in /var/opensocial/modules/authoauth2/lib/Providers/AdjustableGenericProvider.php on line 10, referer: https://sso.example.me/simplesaml/module.php/core/authenticate.php
`

Would you please help me how to fix this?

**Comment by pradtke** [comment]
@umardraz What version of SSP are you using? What command did you use to install the module?  It sounds like composer did not install `league/oauth2-client` dependency. You could try installing that manually with `composer install league/oauth2-client`

**Comment by umardraz** [comment]
Hi **pradtke**, 

The installation was wrong, so I have reinstalled it again and now it start working. Thanks
