### ISSUE TITLE
No Release since january?

### ISSUE THREAD

**Issue by DennisDobslaf** [cirrusidentity/simplesamlphp-module-authoauth2#30]
Hi,

I found this repo for the usage of OpenIdConnect. But the correspending class Auth/Source/OpenIDConnect only exists in master branch. There is no release since Jan. 
Do you plan to make a relase with OpenIDConnect soon?

Greetings,

Dennis

**Comment by pradtke** [comment]
Hi @DennisDobslaf Thanks for the reminder. I had run into some time constraints getting all the tests to work across all the various php versions after the OpenIdConnect class and SSP 1.17 version update were merged in. I've resolved those and [released a v3.0.0 today](https://packagist.org/packages/cirrusidentity/simplesamlphp-module-authoauth2#v3.0.0).
