### ISSUE TITLE
log does not show https messages

### ISSUE THREAD

**Issue by pitufo1972** [cirrusidentity/simplesamlphp-module-authoauth2#47]
hi

in my authsources.php, I have well put the logging to true :
              'logHttpTraffic' => true, //default is false
              'logMessageFormat' => 'A Guzzle MessageFormatter format string', // default setting is sufficient for most debugging
              'logIdTokenJson' => true, //default false. Log the json in the ID token.
but the log only showed the error that I put in my first post "support of opaque access token"
it does not show the actual exchange of https messages that could help me in the future if I have another problem and don't want to bother you
am I missing something in the configuration ?

thanks again for your support

**Comment by pitufo1972** [comment]
here's what I see in my simplesamlphp.log file
it shows the messages exchanged via the browser but does not show the back-end to back-end dialog to exchange the authorization code into ID token and access token

Apr 22 10:48:45 simplesamlphp ERROR [TR95853020] Error loading session: Cannot load PHP session with a specific ID.
Apr 22 10:48:46 simplesamlphp DEBUG [3f1081ac81] Session: 'oauth2' not valid because we are not authenticated.
Apr 22 10:48:46 simplesamlphp DEBUG [3f1081ac81] authoauth2: Enable traffic logging
Apr 22 10:48:46 simplesamlphp DEBUG [3f1081ac81] Saved state: '_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0:https://XXX/simplesaml/module.php/core/as_login.php?AuthId=oauth2&ReturnTo=https%3A%2F%2FXXX%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%3F
as%3Doauth2'
Apr 22 10:48:46 simplesamlphp DEBUG [3f1081ac81] authoauth2:  saved state with stateID=_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0:https://XXX/simplesaml/module.php/core/as_login.php?AuthId=oauth2&ReturnTo=https%3A%2F%2FXXX%2Fsimplesaml%2Fmodule.php%2Fco
re%2Fauthenticate.php%3Fas%3Doauth2
Apr 22 10:48:46 simplesamlphp DEBUG [3f1081ac81] authoauth2:  redirecting to authorizeURL=https://ZZZ/oidc/authorize?state=authoauth2%7C_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0%3Ahttps%3A%2F%2FXXX%2Fsimplesaml%2Fmodule.php%2Fcore%2Fas_l
ogin.php%3FAuthId%3Doauth2%26ReturnTo%3Dhttps%253A%252F%252FXXX%252Fsimplesaml%252Fmodule.php%252Fcore%252Fauthenticate.php%253Fas%253Doauth2&scope=openid%20ecare&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2FXXX%2Fsimplesaml%2Fmodul
e.php%2Fauthoauth2%2Flinkback.php&client_id=IdAqyNzxVC
Apr 22 10:49:09 simplesamlphp DEBUG [3f1081ac81] authoauth2: linkback request=array (
  'code' => 'EEE-ec978d8c2cc95117c9c172c6e71da58f33d22f80f71fc3070d981b4502ae49e0d6e82cb60a7d4a57cbebda6a263051877bba',
  'state' => 'authoauth2|_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0:https://XXX/simplesaml/module.php/core/as_login.php?AuthId=oauth2&ReturnTo=https%3A%2F%2FXXX%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%3Fas%3Doauth2',
)
Apr 22 10:49:09 simplesamlphp DEBUG [3f1081ac81] Loading state: '_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0:https://XXX/simplesaml/module.php/core/as_login.php?AuthId=oauth2&ReturnTo=https%3A%2F%2FXXX%2Fsimplesaml%2Fmodule.php%2Fcore%2Fauthenticate.php%
3Fas%3Doauth2'
Apr 22 10:49:09 simplesamlphp DEBUG [3f1081ac81] authoauth2: Enable traffic logging
Apr 22 10:49:10 simplesamlphp INFO [3f1081ac81] authoauth2:  A Guzzle MessageFormatter format string
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] authoauth2:  id_token json: {"iss":"https://ZZZ","sub":"2hjik2jMxFxAgKc06YOn_Q==","aud":["SSS"],"exp":1619084947,"iat":1619081347,"auth_time":1619081346}
Apr 22 10:49:10 simplesamlphp INFO [3f1081ac81] authoauth2:  A Guzzle MessageFormatter format string
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] authoauth2:  attributes: someprefix.sub
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] authoauth2:  finished authentication in 0.41816401481628 seconds
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Deleting state: '_ca3ba1aef463b522b5cd68df13e5345f36f48a9eb0'
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Session: doLogin("oauth2")
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Session: Valid session found with 'oauth2'.
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Session: Valid session found with 'oauth2'.
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Session: Valid session found with 'oauth2'.
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Localization: using old system
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Session: Valid session found with 'oauth2'.
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Translate: Reading dictionary [/var/simplesamlphp/dictionaries/status]
Apr 22 10:49:10 simplesamlphp DEBUG [3f1081ac81] Translate: Reading dictionary [/var/simplesamlphp/dictionaries/attributes]

**Comment by pradtke** [comment]
You set your logFormat to `'logMessageFormat' => 'A Guzzle MessageFormatter format string',`    That tells guzzle to log he text `A Guzzle MessageFormatter format string`. You should change that to a MessageFormatter string that Guzzle supports, or if you leave out `logMessageFormat` then the library will use a default format string for logging.

**Comment by pitufo1972** [comment]
hi
you are right, I replaced with following values in Authsources.php and get now a full trace of back-end dialogs:
'logHttpTraffic' => true, //default is false
'logMessageFormat' => '{request} <br> {response}', 
'logIdTokenJson' => true, //default false. Log the json in the ID token.

tx
