### ISSUE TITLE
OpenID full metadata URL

### ISSUE THREAD

**Issue by pablopoo** [cirrusidentity/simplesamlphp-module-authoauth2#52]
On Microsoft Azure, there is a way to change the oauth2 certificates per "app". 
To get the correct certificate, the app ID must be passed as query parameter, so

`https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration`

returns different certificates as:

`https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration?appid={client-id}`

I didn't found a parameter to specify the full metadata url, to override the issuer url that is completed in the backend with the path ".well-known/openid-configuration"

**Comment by pradtke** [comment]
Fix will be part of the SSP v2 release.

`discoveryUrl` can now be explicitly set.

**Comment by pradtke** [comment]
Part of `v4.0.0-beta.1`
