### ISSUE TITLE
Updates for SSP2

### ISSUE THREAD

**Issue by ghalse** [cirrusidentity/simplesamlphp-module-authoauth2#66]
SimpleSAMLphp 2.0.0 is [available as a release candidate](https://github.com/simplesamlphp/simplesamlphp/releases/tag/v2.0.0-rc2), and requires some updates to modules. The gist of what's required is documented at https://simplesamlphp.org/docs/devel/simplesamlphp-upgrade-notes-2.0.html#changes-relevant-for-module-developers

Is it possible to update this module to support SSP2?

**Comment by pradtke** [comment]
Hi @ghalse I hope to have time to start on that soon. I've been hoping for that for about a year, but now that SSP v2 is very close to release it has become a priority for us as well.  When I have a SSP v2 branch ready,  do you have an environment to help validate it in? If so, which OPs to you integrate with? (just so I have a better idea of what test coverage we can achieve). No worries if the answer is no.

**Comment by ghalse** [comment]
Hi @pradtke, yes, our dev environment is staging SSP2 in preparation for its release. That's how I picked this up :). We're using Google, Microsoft, and ORCID (the latter via a fork of cilogin's plugin)

**Comment by pradtke** [comment]
eventual home for sspv2 version will be https://github.com/cirrusidentity/simplesamlphp-module-authoauth2/tree/ssp2

**Comment by pradtke** [comment]
There is a version available to test v4.0.0-alpha.1
I ran through some tests with Google, Facebook and Microsoft on php 8.1 and release candidate 2 of SSP 2.

**Comment by ghalse** [comment]
I've also successfully managed to do the same (PHP 8.1; SSP 2.0.0-rc2). In addition to those three, I tested with LinkedIn and ORCID as well.

**Comment by pradtke** [comment]
@ghalse There is now `v4.0.0-beta.1` which should work with SSP 2. (Between SSP2 rc2 and rc3 the `www` folder needed to get renamed to `public`)

**Comment by ghalse** [comment]
It seems to work for me :-)

**Comment by jimcottrell** [comment]
What would it take to move this forward and get a stable 4.x release? Should I put together PRs for #69 and #70?

**Comment by pradtke** [comment]
@jimcottrell I have tagged a new stable (it is the same code as the beta tags, since nothing changed).  It turns out #69 and #70 are not required for SSP 2 - the old way of doing templates and www interactions still works. I'm not sure when SSP2 will remove support for the old way, so if you do have time and resources for tackling either, it would be much appreciated.

**Comment by jimcottrell** [comment]
Excellent. Thanks, @pradtke! I'll look into #69 and #70 further when I get a chance.
