### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by pitufo1972** [cirrusidentity/simplesamlphp-module-authoauth2#75]
hi,
using authoauth2 with an IDP, I'm correctly getting an autorization code but while calling /token to exchange that authorization to get access token and id token I'm getting error "cURL error 60: SSL certificate problem: unable to get local issuer certificate
I've done manually the curl and correctly get the response so the issue is specifically using simplesamlphp & cirrusidentity library

I've also tried to download the cacert from https://curl.se/docs/caextract.html and put it in /var/simplesamlphp/cert/ directory and restart apache2 but not change
I've also added the certificate chain of the /token but still no change

can you advise what to do to solve this ?

tx,
           Christophe

**Comment by pradtke** [comment]
@pitufo1972 did you ever figure out this issue? It sounds like php on your system is not configured with CA for the OAuth2 server. How to configure that is going to OS and php version dependent.

This linke https://stackoverflow.com/a/31253824 has details on how to determine where to put the cacert on your system.  `/var/simplesamlphp/cert/` is not that location.  `/var/simplesamlphp/cert/` is where SSP stores its SAML signing and encryption certificates and is not involved with TLS.
