### ISSUE TITLE
Hard dependency on psr/cache 1.0

### ISSUE THREAD

**Issue by dnmvisser** [cirrusidentity/simplesamlphp-module-authoauth2#82]
Latest SimpleSAMLphp has bumped its dependency on `psr/cache` to `2.0.0`: https://github.com/simplesamlphp/simplesamlphp/blob/v2.0.5/composer.lock#L1012

This conflicts with the `^1.0` requirement here: https://github.com/cirrusidentity/simplesamlphp-module-authoauth2/blob/v4.0.0-beta.1/composer.json#L18

**Comment by pradtke** [comment]
@dnmvisser Thanks for catching this.   I think I have it fixed in `v4.0.0-beta.2`.  Let me know if that resolves it for you and we can close this issue.

**Comment by dnmvisser** [comment]
@pradtke seems to work, many thx :)
