### ISSUE TITLE
Google Readme Example using Google Plus API

### ISSUE THREAD

**Issue by precurse** [cirrusidentity/simplesamlphp-module-authoauth2#9]
Hello,

The Generic Google example in the readme shows the following Google plus endpoint in the example:
```
https://www.googleapis.com/plus/v1/people/me/openIdConnect
```
Is there any particular reason for using the Google plus endpoint as opposed to the OAuth2 endpoint shown in the OIDC Google Docs at https://developers.google.com/identity/protocols/OpenIDConnect ?:
```
https://www.googleapis.com/oauth2/v3/userinfo
```
I was just curious since I'm using the API in the example, but wanting to make sure there's no particular reason that we can't use the latter.

Thanks!

**Comment by pradtke** [comment]
I'd follow what is in [Google specific docs](https://github.com/cirrusidentity/simplesamlphp-module-authoauth2/blob/master/docs/GOOGLE.md). 

I'll leave this ticket open so I can go through the main README and remove the old generic config information.

**Comment by precurse** [comment]
Perfect, thanks for the help!

**Comment by pradtke** [comment]
README has been cleaned up. closing issue.
