### ISSUE TITLE
Problem with Curl using the module

### ISSUE THREAD

**Issue by luandalmazo** [cirrusidentity/simplesamlphp-module-authoauth2#91]
Hi!

I am having a problem with the module; I am using the module as an RP to communicate with a module from SSP that offers support to OP (the same one recommended in the README file from this module). The problem arises when I select the authentication source that is configured, it returns this error:

Caused by: GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 3001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ssp-instance-op-suport/simplesaml/module.php/oidc/token.php

My authentication file is configured as follows:

```
'test' => [
    'authoauth2:OAuth2',
    'urlAuthorize' => 'https://ssp-instance-op-suport/simplesaml/module.php/oidc/authorize.php',
    'urlAccessToken' => 'https://ssp-instance-op-suport/simplesaml/module.php/oidc/token.php',
    'urlResourceOwnerDetails' => 'https://ssp-instance-op-suport/simplesaml/module.php/oidc/userinfo.php',
    'clientId' => 'MyClientID',
    'clientSecret' => 'MyClientSecret',
    'scopes' => ['profile'],
],
```

My configuration of a client in the "ssp-instance-op-suport" uses the default callback URL from this module as the redirect URI. The scopes described there are: openid and profile, and the authentication source is default-sp.

I have previously used the module with the OIDC protocol, but encountered an error related to the well-known configuration (it seems that the application can't retrieve the well-known address from the other module). Additionally, I have tested both the OP and RP instances individually; the OP instance was tested with Keycloak and worked well, while the RP instance was tested with Satosa and also worked well.

Any insights or suggestions on resolving this issue would be greatly appreciated!

**Comment by pradtke** [comment]
I think start with increasing the timeout in your OAuth2 authsource config

```
              'timeout' => 30,
```

but your comment about the module being unable to retrieve a the `well-known` file makes it sound like the RP server is unable to connect to the OP server.  Maybe do some tests from the command line with `curl` to see if the RP server can reach the OP server.

**Comment by luandalmazo** [comment]
I increased the timeout duration, but the error was still appearing. After conducting some tests involving Curl in the VM, I discovered that the problem was with the VM's network.
